/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./src/assets/matterhorn/matterhorn.gltf --keepnames --keepgroups --types
Author: jawensi (https://sketchfab.com/jawensi)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/matterhorn-130000-demto3d-cc16427e01814381b68b09ebd01dcd6c
Title: Matterhorn 1:30.000 (DEMto3D)
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		Object_2: THREE.Mesh
	}
	materials: {
		['Scene_-_Root']: THREE.MeshStandardMaterial
	}
}

export default function Matterhorn(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('matterhorn/scene.gltf') as GLTFResult
	return (
		<group {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
					<group name="3ecea069965c4a7486f9e47d1c6347e6stlcleaner">
						<mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
					</group>
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('matterhorn/scene.gltf')
